# Generated by Django 5.0.5 on 2024-05-20 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.CharField(max_length=1000)),
                ('paginas', models.IntegerField()),
                ('descricao', models.CharField(max_length=1000)),
                ('formato', models.CharField(choices=[('E', 'E-BOOK'), ('F', 'FISICO')], max_length=30)),
                ('n_edicao', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('ano_pub', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=1)),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrosCategorias', to='main.categorias')),
            ],
        ),
    ]
