# Generated by Django 5.0.5 on 2024-05-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='autor',
            new_name='autorFK',
        ),
    ]
