# Generated by Django 5.0.5 on 2024-05-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_autores_remove_emprestimo_livrofk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(max_length=50),
        ),
    ]
