# Generated by Django 5.0.5 on 2024-05-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_livros_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emprestimoLivros',
        ),
    ]
